### ISSUE TITLE
Structure package (creation of collection, schema and indexes)

### ISSUE THREAD

**Issue by PEM--** [spacedrop/spacedrop#2]
Yep. Found you :smile: 

What type of licensing have you chosen for this CMS?

There are some stuff that I would like to share. However, I need to check if your license matches mine (MIT).

**Comment by nabiltntn** [comment]
Things from Orion :) ?

**Comment by PEM--** [comment]
Ha ha :smile:  Nope. Though, the isomorphic logger could help for enterprise adoption.

The approach taken here on ES2015 and React is quite appealing. The capability to inherit from a template is more straightforward. Plus the SSR capabilities of React brings what's missing to a good SEO on other approach (at least if you don't want to install Phantom).

**Comment by PEM--** [comment]
Actually, I was thinking of pushing a package here that simplifies the creation of collections filled with defaults, Schema, Mongo indexes and verified subscription as a small class.

**Comment by timbrandin** [comment]
Yes, MIT LGTM

**Comment by timbrandin** [comment]
PEM, :+1: for standardizing collection and schema creation, I'm also planning a package that gives a UI to create these things. Important learnings from Drupal is to have good separation of content and configuration, to allow for updates without messing with content.

In Drupal 8 they've added a sort of configuration management that has storages both in the database and in code, I'd prefer something like it but with an aspect of never allowing for changes of configuration on a live application, or otherwise some way of syncing configuration between production, stage and local development environments.

**Comment by timbrandin** [comment]
I've incorporated your ideas into the README now, would be nice to get a review of it.

**Comment by PEM--** [comment]
Super nice. I've added few additional stuff.

The current implementation of the collection helpers is here: https://github.com/PEM--/congres-avef-snvel/blob/master/app/packages/col-basecollection/col-basecollection.js

It needs some JSDocs, documentation usage but it has already indexes, schema, defaults.

I'm currently tight on my deadlines for my customers. I should be able to dedicate more time by the end of the next week.

**Comment by timbrandin** [comment]
Prefect, also we're planning a hangout after the Meteor Hackathon to kick of the project. Also I have a lot on my hands up until then so will be sparse on time next two week, I'm giving a speech at a conference and arranging a local instance of the Hackathon.

Great, let's always try to use existing code from meteor packages. :+1:
